dist: xenial
sudo: required
language: rust
rust: 1.31.0
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - COQ_VERSION="8.8.0"

install:
- which fd || cargo install fd-find
- file `which fd`
- opam --version
- "[ -e .opam ] || opam init -j ${NJOBS} -n -y"
- eval $(opam config env)
- opam config list
- opam config var root
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
- opam update
- opam show coq
- travis_wait opam install -j ${NJOBS} -y coq=${COQ_VERSION} ${EXTRA_OPAM}
- opam list
- file `which coqc`

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.opam.cached
  - $HOME/.opam
  - $HOME/local

stages:
  - build

jobs:
  include:
  - stage: build
    script:
    - make -j ${NJOBS}
