dist: trusty
sudo: required
language: ocaml
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - COMPILER="system"
  - COQ_VERSION="8.8.0"
  - NEXT_VERSION="8.8.1"

install:
- opam --version
- "[ -e .opam ] || opam init -j ${NJOBS} -n -y"
- opam switch ${COMPILER}
- eval $(opam config env)
- opam config list
- opam config var root
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || true
- opam update
- opam show coq
- opam install -j ${NJOBS} -y coq=${COQ_VERSION} ${EXTRA_OPAM}
- opam list
- file `which coqc`

stages:
  - build

jobs:
  include:
  - stage: build
    script:
    - make -j ${NJOBS}
